### ISSUE TITLE
Remove Welcome Voice and Notification

### ISSUE THREAD

**Issue by PrimalPimmy** [osPrims/chatApp#161]
We need to remove the "Welcome to chatApp, Instant messaging at your service" voice, since it is not necessary. This also includes the notification sounds. Remove any code belonging to this feature, including the mp3 files.

Check out this function here, and other similar functions in client.js , and remove any code that plays sound.
https://github.com/osPrims/chatApp/blob/f612192999d6722bff509b055eaaf8a829e0dd00/public/client.js#L126

There are some more instances of playSound() here.

**Comment by KossakowskaKarolina** [comment]
Hello, I would work on this issue.

**Comment by PrimalPimmy** [comment]
Hi @KossakowskaKarolina , we're reserving all good first issues for absolute beginners, who have little to no experience in web dev. You can checkout our other non goodfirstissues :D

**Comment by KossakowskaKarolina** [comment]
I absolutely understand, that's why I've been looking for that kind of issues :) Trying to do my first contibution. I'll give another one a try.

**Comment by PrimalPimmy** [comment]
The other issues might not be that tough, for example a good dark mode UI would be nice to have :D

**Comment by MohitSinghChauhan** [comment]
I want to work on this, Assign it to me :)

**Comment by abhis1n** [comment]
Hello, I would like to make a contribution to this issue.

**Comment by PrimalPimmy** [comment]
Hey @Ocidemus , thanks for showing interest in this, assigning this to you!
