### ISSUE TITLE
Make a SETUP.md file

### ISSUE THREAD

**Issue by PrimalPimmy** [osPrims/chatApp#164]
Currently our setup instructions are in the README.md file, but we want it to be a separate file.

**Comment by Pranjalmishra30** [comment]
Hi I would like to contribute to this issue

**Comment by osBins** [comment]
Hi @Pranjalmishra30, we're reserving this issue for a beginner.
Feel free to take a look at the other issues and let us know if you'll be taking it up. Thank you for understanding!

**Comment by Pranjalmishra30** [comment]
Sure will check other issues

**Comment by PrimalPimmy** [comment]
Any issue other than goodfirstissue should be fine :+1:

**Comment by abhis1n** [comment]
Hello, I would like to make a contribution to this issue.
