### ISSUE TITLE
Replace badges in README.md with cooler badges

### ISSUE THREAD

**Issue by osBins** [osPrims/chatApp#166]
Current badges in the README by [shields.io](https://shields.io) can be replaced.
We can use the `flat-square` style on shields.io while generating badges for the repository for this.

**Comment by GamerWhoDoesntGame** [comment]
Hey @osBins, Can i work on this issue?

**Comment by osBins** [comment]
Sure! Assigning the issue to you.

**Comment by GamerWhoDoesntGame** [comment]
Thanks a lot. I'm looking forward to it :)
