### ISSUE TITLE
fix inconsistent badges in README

### ISSUE THREAD

**Issue by osBins** [osPrims/chatApp#170]
https://github.com/osPrims/chatApp/blob/fcf7cd9731fc05c4e014a789434151c0be03a022/README.md?plain=1#L6-L9

The 'Issues' and 'Pull Requests' badges -
* should have consistent style with the 'forks' and 'stars' issue (flat-square)

The 'Forks' and 'Star' badges -
* should not have a logo in them

Required fix would be to correct the query parameters used for the badges.

**Comment by krishnanshagarwal112** [comment]
I think the 'Issues' and 'Pull Requests' issue is resolved already ?

**Comment by osBins** [comment]
Resolved via #186
