### ISSUE TITLE
receiving all the chat messages again and again and it's maybe due to some issue with socket.io

### ISSUE THREAD

**Issue by ozair-dev** [osPrims/chatApp#189]
So I signed in with my account and left the website open for a while and noticed a problem.
I saw that after every few minutes, the chat shows a message that a new user has connected, and all messages (and I mean all of em from start to bottom) are appended again to the chat which should not happen, and whats weird is that the new recognized user is in fact me. So it thinks that i have reloaded the page or something and it gets all the messages again. Why is this showing the new user (which is me) connected message when I didn't even left the chat and neither did I reload the page. And it keeps happening unlimitedly.

In the screenshot, you can see that it is showing my name multiple times in the **online people list**, and also in the **console** it is logging all the messages again and again after few minutes which means it is receiving all messages again and again

![Screenshot from 2022-10-11 22-03-19](https://user-images.githubusercontent.com/65649182/195156191-f9d3254e-9f88-4482-813a-f1575e4c212f.png)

Hope I explained the issue clearly.

I think it has something to do with socket.io. I can dig into this issue if you want me to.

If you understand the issue, and want me to work on it, then assign it to me.

# Steps to reproduce the issue:

- Just load the page https://chatapp-wuhy.onrender.com/ and leave it open for like 10-12 minutes and you'll see that it appends all the messages again to the chat and also adds you to the **online people list**.

**Comment by osBins** [comment]
Good fine @ozair-dev. Thanks for pointing this out. Assigning this issue to you.
