### ISSUE TITLE
Disable HTML functionality in chatApp

### ISSUE THREAD

**Issue by vridhi4** [osPrims/chatApp#191]

**Comment by vridhi4** [comment]
@osBins Please assign me this issue, I would like to work on it.

**Comment by osBins** [comment]
We are using `markdown-it` package on NPM to handle markdown/html parsing in the chat app messages.  
https://github.com/markdown-it/markdown-it#init-with-presets-and-options shows the flags we can set for markdown/html rendering.  
This issue requires a simple flag change from `true` to `false` in `client.js` at -  
https://github.com/osPrims/chatApp/blob/2bf8047fb5683358e49b82bc3dcdc542f0c1cbb5/public/js/client.js#L19-L25
