### ISSUE TITLE
Adding "Send Location" button

### ISSUE THREAD

**Issue by Tripat-Jot** [osPrims/chatApp#53]

**Comment by osBins** [comment]
Hey @Tripat-Jot. That's a cool idea. Can you edit the issue title to just say "Adding 'send location button'" or something of the sorts so that the title is brief, and then explain it briefly in the description?

**Comment by osBins** [comment]
@Tripat-Jot can you update me on this issue's progress?

**Comment by Shreya-Agrawal-2121** [comment]
I would like to work on this issue. Can this be assigned to me?

**Comment by osBins** [comment]
Alright. Since it has been more than 2 weeks and I haven't received a response yet from @Tripat-Jot, I'm assigning this issue to you @Shreya-Agrawal-2121! Let me know if you face any issues. Good luck!
